/* ==========================================================================
   PuzzleWindow — the classic Mac "Puzzle" desk accessory: a 4×4 frame with
   15 numbered tiles and one gap. Click a tile in the blank's row or column
   to slide the whole segment. Shuffles are generated by random legal moves,
   so every deal is solvable. Arrow keys work too.
   ========================================================================== */

import { useEffect, useRef, useState } from 'react';
import { unlockAchievement } from '../lib/achievements';
import { playTileSlide } from '../lib/sounds';

const N = 4;
const CELLS = N * N;
const SHUFFLE_MOVES = 220;

/** board[i] = tile number at cell i, 0 = the blank */
type Board = number[];

const SOLVED: Board = [...Array(CELLS - 1).keys()].map((i) => i + 1).concat(0);

function isSolved(b: Board): boolean {
  return b.every((v, i) => v === SOLVED[i]);
}

/** Cells adjacent to the blank (single-tile legal moves) */
function neighborsOfBlank(b: Board): number[] {
  const blank = b.indexOf(0);
  const r = Math.floor(blank / N);
  const c = blank % N;
  const out: number[] = [];
  if (r > 0) out.push(blank - N);
  if (r < N - 1) out.push(blank + N);
  if (c > 0) out.push(blank - 1);
  if (c < N - 1) out.push(blank + 1);
  return out;
}

/** Shuffle by walking random legal moves from solved — always solvable. */
function shuffled(): Board {
  const b = [...SOLVED];
  let prevBlank = -1;
  for (let i = 0; i < SHUFFLE_MOVES; i++) {
    const blank = b.indexOf(0);
    const options = neighborsOfBlank(b).filter((n) => n !== prevBlank);
    const pick = options[Math.floor(Math.random() * options.length)];
    b[blank] = b[pick];
    b[pick] = 0;
    prevBlank = blank;
  }
  if (isSolved(b)) return shuffled(); // astronomically unlikely, but free
  return b;
}

/** Slide toward the blank: clicking any cell in the blank's row/column
    shifts every tile between it and the blank by one (classic behaviour).
    Returns null if the click wasn't in line with the blank. */
function slide(b: Board, cell: number): Board | null {
  const blank = b.indexOf(0);
  if (cell === blank) return null;
  const br = Math.floor(blank / N);
  const bc = blank % N;
  const cr = Math.floor(cell / N);
  const cc = cell % N;
  if (br !== cr && bc !== cc) return null;

  const next = [...b];
  const step = br === cr ? (cc > bc ? 1 : -1) : cr > br ? N : -N;
  let gap = blank;
  while (gap !== cell) {
    const from = gap + step;
    next[gap] = next[from];
    next[from] = 0;
    gap = from;
  }
  return next;
}

export default function PuzzleWindow() {
  const [board, setBoard] = useState<Board>(shuffled);
  const [moves, setMoves] = useState(0);
  const [won, setWon] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    rootRef.current?.focus();
  }, []);

  const doSlide = (cell: number) => {
    if (won) return;
    const next = slide(board, cell);
    if (!next) return;
    playTileSlide();
    setBoard(next);
    setMoves((m) => m + 1);
    if (isSolved(next)) {
      setWon(true);
      unlockAchievement('puzzle-solve');
    }
  };

  const newGame = () => {
    setBoard(shuffled());
    setMoves(0);
    setWon(false);
    rootRef.current?.focus();
  };

  /** Arrow keys move the tile on that side of the blank into the gap. */
  const onKeyDown = (e: React.KeyboardEvent) => {
    const blank = board.indexOf(0);
    const r = Math.floor(blank / N);
    const c = blank % N;
    let cell = -1;
    if (e.key === 'ArrowUp' && r < N - 1) cell = blank + N;
    else if (e.key === 'ArrowDown' && r > 0) cell = blank - N;
    else if (e.key === 'ArrowLeft' && c < N - 1) cell = blank + 1;
    else if (e.key === 'ArrowRight' && c > 0) cell = blank - 1;
    else if (e.key.toLowerCase() === 'n') {
      e.preventDefault();
      newGame();
      return;
    }
    if (cell >= 0) {
      e.preventDefault();
      doSlide(cell);
    }
  };

  return (
    <div
      ref={rootRef}
      className="puzzle-content"
      tabIndex={0}
      onKeyDown={onKeyDown}
    >
      <div className="puzzle-status">
        <span className="paint-bar-label">Moves: {moves}</span>
        <span className="paint-bar-label">{won ? 'Solved!' : ''}</span>
      </div>

      <div className={`puzzle-frame${won ? ' solved' : ''}`}>
        {board.map((tile, i) =>
          tile === 0 ? (
            <span key="blank" className="puzzle-blank" />
          ) : (
            <button
              key={tile}
              type="button"
              className="puzzle-tile"
              onClick={() => doSlide(i)}
              aria-label={`Tile ${tile}`}
            >
              {tile}
            </button>
          ),
        )}
      </div>

      <div className="puzzle-footer">
        <button type="button" className="mac-button" onClick={newGame}>
          New Game
        </button>
        <span className="win-meta">Click a tile in line with the gap.</span>
      </div>
    </div>
  );
}
